version: '2.2'
services:
  fuggle_base:
    image: fuggle:base
    build: .
  fuggle_dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "5000:80"
      - "5555:5555"
      - "3449:3449"
    volumes:
      - ${HOME}/.m2:/root/.m2
      - ${HOME}/.aws:/root/.aws
      - ./:/opt/fuggle
    command: lein repl :headless :host 0.0.0.0 :port 5555
    depends_on:
      - fuggle_base
